name: collis
favicon: null
layout_spectrum: 0.29522921121679246
typography_spectrum: 0.9470497323200107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2847169782035053
  lightness: 0.8383270716294646
  saturation: 0.6618374784011394
  rhythmicContrast: 0.9395165406167507
purpose: []
